// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQRB5mKcqMIxv27BylGV6qVQYySdY7o8',
    appId: '1:606334525058:web:d5a0dc49a94d47ab50de9b',
    messagingSenderId: '606334525058',
    projectId: 'queens-connect-1ab54',
    authDomain: 'queens-connect-1ab54.firebaseapp.com',
    storageBucket: 'queens-connect-1ab54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWRnQQGHh98mTl35b8Esad8F3C0cBNjE',
    appId: '1:606334525058:android:256ed2dbfc43d50950de9b',
    messagingSenderId: '606334525058',
    projectId: 'queens-connect-1ab54',
    storageBucket: 'queens-connect-1ab54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt8tc0sTkFjKL8rXKl8ZN-iCZuWrsbuoM',
    appId: '1:606334525058:ios:b8828615ea73dcea50de9b',
    messagingSenderId: '606334525058',
    projectId: 'queens-connect-1ab54',
    storageBucket: 'queens-connect-1ab54.firebasestorage.app',
    iosBundleId: 'com.example.hospitalFieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt8tc0sTkFjKL8rXKl8ZN-iCZuWrsbuoM',
    appId: '1:606334525058:ios:b8828615ea73dcea50de9b',
    messagingSenderId: '606334525058',
    projectId: 'queens-connect-1ab54',
    storageBucket: 'queens-connect-1ab54.firebasestorage.app',
    iosBundleId: 'com.example.hospitalFieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfQRB5mKcqMIxv27BylGV6qVQYySdY7o8',
    appId: '1:606334525058:web:4894241f6f833f8450de9b',
    messagingSenderId: '606334525058',
    projectId: 'queens-connect-1ab54',
    authDomain: 'queens-connect-1ab54.firebaseapp.com',
    storageBucket: 'queens-connect-1ab54.firebasestorage.app',
  );

}